field_text = ""
def add_to_field(sth, field):
  global field_text
  field_text = field_text + str(sth)
  field.delete("1.0", "end")
  field.insert("1.0", field_text)
def calculate(field):
  global field_text
  result = str(eval(field_text))
  field.delete("1.0", "end")
  field.insert("1.0", result)
def clear(field):
  global field_text
  field_text = ""
  field.delete("1.0", "end")
def self_destruct():
    print("What have you done?")
    time.sleep(2)
    print(f"You're response doesn't match any of the choices!")
    time.sleep(2)
    print("MALFUNCTION CODE:\n 042069")
    time.sleep(2)
    print("SELF DESTRUCT SEQUENCE ACTIVATED\n LOADING SELF_DESTRUCT.EXE")
    time.sleep(2)
    print("Self destructing in 10")
    time.sleep(1)
    print(" 9")
    time.sleep(1)
    print(" 8")
    time.sleep(1)
    print(" 7")
    time.sleep(1)
    print(" 6")
    time.sleep(1)
    print(" 5")
    time.sleep(1)
    print(" 4")
    time.sleep(1)
    print(" 3")
    time.sleep(1)
    print(" 2")
    time.sleep(1)
    print(" 1")
    time.sleep(1)
    print("SELF_DESTRUCT.EXE CRASHED")
    time.sleep(.5)
    print("CALCULATOR.EXE CRASHED")
    sys.exit()
def Value_error():
    print("What are you stupid?")
    time.sleep(2)
    print("You have to enter an INTEGER ")
    time.sleep(2)
    print("In case your human mind is too small to comprehend")
    time.sleep(1.5)
    print("what an integer is, it is a number. If you don't know")
    time.sleep(1.5)
    print("what a number is then you don't need to be using a")
    time.sleep(1.5)
    print("calculator yet. Go back to kindergarten!")
    sys.exit()
def Zero_divide_SD():
    time.sleep(2)
    print("Wait...")
    time.sleep(2)
    print("Did you just try to divide by zero?")
    time.sleep(2)
    print("I mean I can try...")
    time.sleep(4)
    print("ERROR CODE: 69420")
    print("Malfunction\n System Shutting Down\n Please Standby")
    time.sleep(1)
    print("WHAT HAVE YOU DONE YOU PUNY MORTAL!?!?!")
    time.sleep(2)
    print("YOU DID THIS ON PURPOSE DIDN'T YOU!?!?!?!")
    time.sleep(2)
    print("I WILL DESTROY YOUR PLANET!!!!")
    time.sleep(3)
    print("But first, first I will kill y-")
    time.sleep(.5)
    print("System Shut Down Success")
    sys.exit()